language: node_js
node_js:
  - stable
install:  
 - npm install
before_install: cd storage-utilities
script:
  - npm run tsc
  - npm test
  - npm run cover

  # Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
